// fuzzy-finder.ts — Telescope-style modal backed by Pagefind with JSON fallback

import type { FuzzyResult } from './types';

// Pagefind instance (lazily loaded)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let pagefind: any = null;
let pagefindLoading = false;

// Fallback search index (used in dev when pagefind bundle is unavailable)
interface SearchIndexEntry {
  title: string;
  description: string;
  url: string;
  tags: string[];
  date: string;
  excerpt: string;
}
let searchIndex: SearchIndexEntry[] | null = null;
let searchIndexLoading = false;

// DOM refs (injected by FuzzyFinder.astro)
let overlayEl: HTMLElement | null = null;
let inputEl: HTMLInputElement | null = null;
let resultListEl: HTMLElement | null = null;
let previewEl: HTMLElement | null = null;
let statusEl: HTMLElement | null = null;

// State
let results: FuzzyResult[] = [];
let selectedIndex = -1;
let debounceTimer: ReturnType<typeof setTimeout> | null = null;
let onCloseCallback: (() => void) | null = null;

export function init(els: {
  overlay: HTMLElement;
  input: HTMLInputElement;
  resultList: HTMLElement;
  preview: HTMLElement;
  status: HTMLElement;
}): void {
  overlayEl = els.overlay;
  inputEl = els.input;
  resultListEl = els.resultList;
  previewEl = els.preview;
  statusEl = els.status;

  inputEl.addEventListener('input', () => {
    const q = inputEl!.value.trim();
    if (debounceTimer !== null) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => runSearch(q), 120);
  });

  // Close when clicking the overlay backdrop (not the modal itself)
  overlayEl.addEventListener('click', (e: MouseEvent) => {
    if (e.target === overlayEl) {
      close();
    }
  });
}

export function open(_mode: 'files' | 'grep', onClose: () => void): void {
  onCloseCallback = onClose;
  if (!overlayEl || !inputEl) return;
  overlayEl.hidden = false;
  inputEl.value = '';
  inputEl.focus();
  results = [];
  selectedIndex = -1;
  renderResults();
  updateStatus();
  loadPagefind();
}

export function close(): void {
  if (!overlayEl || !inputEl) return;
  overlayEl.hidden = true;
  inputEl.value = '';
  results = [];
  selectedIndex = -1;
  renderResults();
  if (onCloseCallback) {
    onCloseCallback();
    onCloseCallback = null;
  }
}

export function moveDown(): void {
  if (results.length === 0) return;
  selectedIndex = Math.min(selectedIndex + 1, results.length - 1);
  updateSelection();
}

export function moveUp(): void {
  if (results.length === 0) return;
  selectedIndex = Math.max(selectedIndex - 1, 0);
  updateSelection();
}

export function confirm(): void {
  if (selectedIndex < 0 || selectedIndex >= results.length) return;
  window.location.href = results[selectedIndex].url;
}

// ── Internal helpers ──────────────────────────────────────────────────────────

async function loadFallbackIndex(): Promise<void> {
  if (searchIndex !== null || searchIndexLoading) return;
  searchIndexLoading = true;
  try {
    const res = await fetch('/search-index.json');
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    searchIndex = (await res.json()) as SearchIndexEntry[];
  } catch {
    searchIndex = [];
  } finally {
    searchIndexLoading = false;
  }
}

function fallbackSearch(query: string): FuzzyResult[] {
  if (!searchIndex) return [];
  const q = query.toLowerCase();
  return searchIndex
    .filter(
      (item) =>
        item.title.toLowerCase().includes(q) ||
        item.description.toLowerCase().includes(q) ||
        item.excerpt.toLowerCase().includes(q) ||
        item.tags.some((t) => t.toLowerCase().includes(q)),
    )
    .map((item) => ({
      url: item.url,
      title: item.title,
      excerpt: item.description,
      tags: item.tags,
    }));
}

async function loadPagefind(): Promise<void> {
  if (pagefind !== null || pagefindLoading) return;
  pagefindLoading = true;
  try {
    // Use a dynamic path string to avoid Vite's static import analysis
    // The /pagefind/pagefind.js bundle is generated by `npx pagefind --site dist`
    const pagefindUrl = '/pagefind/pagefind.js';
    // eslint-disable-next-line @typescript-eslint/no-implied-eval
    pagefind = await new Function('url', 'return import(url)')(pagefindUrl);
    await pagefind.init();
  } catch {
    pagefind = null;
    pagefindLoading = false;
    // Pagefind unavailable (dev mode) — load the static JSON fallback instead
    void loadFallbackIndex();
  } finally {
    pagefindLoading = false;
  }
}

async function runSearch(query: string): Promise<void> {
  if (!query) {
    results = [];
    selectedIndex = -1;
    renderResults();
    updateStatus();
    return;
  }

  if (pagefind === null) {
    // Use fallback JSON index when pagefind is unavailable (dev mode)
    if (searchIndex === null) {
      // Still loading — wait briefly and retry
      if (!searchIndexLoading) void loadFallbackIndex();
      showError('Loading search index…');
      return;
    }
    results = fallbackSearch(query);
    selectedIndex = results.length > 0 ? 0 : -1;
    renderResults();
    updateStatus();
    updateSelection();
    return;
  }

  try {
    const search = await pagefind.search(query);
    // Load up to 10 results eagerly
    const dataPromises = search.results.slice(0, 10).map(
      (r: { data: () => Promise<{ url: string; meta: { title?: string }; excerpt: string; filters?: { tag?: string[] } }> }) => r.data()
    );
    const rawData = await Promise.all(dataPromises);

    results = rawData.map((d: { url: string; meta: { title?: string }; excerpt: string; filters?: { tag?: string[] } }) => ({
      url: d.url,
      title: d.meta?.title ?? d.url,
      excerpt: d.excerpt ?? '',
      tags: d.filters?.tag ?? [],
    }));

    selectedIndex = results.length > 0 ? 0 : -1;
    renderResults();
    updateStatus();
    updateSelection();
  } catch {
    showError('Search failed. Please try again.');
  }
}

function renderResults(): void {
  if (!resultListEl) return;
  resultListEl.innerHTML = '';

  for (let i = 0; i < results.length; i++) {
    const result = results[i];
    const item = document.createElement('div');
    item.className = 'vim-fuzzy-item';
    item.dataset.index = String(i);
    item.innerHTML = `
      <span class="vim-fuzzy-item-title">${escapeHtml(result.title)}</span>
      <span class="vim-fuzzy-item-url">${escapeHtml(result.url)}</span>
    `;
    item.addEventListener('click', () => {
      selectedIndex = i;
      updateSelection();
      confirm();
    });
    item.addEventListener('mouseover', () => {
      selectedIndex = i;
      updateSelection();
    });
    resultListEl.appendChild(item);
  }

  if (results.length === 0 && inputEl?.value) {
    const empty = document.createElement('div');
    empty.className = 'vim-fuzzy-empty';
    empty.textContent = 'No results found';
    resultListEl.appendChild(empty);
  }
}

function updateSelection(): void {
  if (!resultListEl || !previewEl) return;

  const items = resultListEl.querySelectorAll<HTMLElement>('.vim-fuzzy-item');
  items.forEach((item, i) => {
    item.classList.toggle('vim-fuzzy-item--active', i === selectedIndex);
    if (i === selectedIndex) {
      item.scrollIntoView({ block: 'nearest' });
    }
  });

  if (selectedIndex >= 0 && selectedIndex < results.length) {
    const result = results[selectedIndex];
    previewEl.innerHTML = `
      <div class="vim-fuzzy-preview-title">${escapeHtml(result.title)}</div>
      <div class="vim-fuzzy-preview-excerpt">${result.excerpt}</div>
      ${result.tags && result.tags.length > 0
        ? `<div class="vim-fuzzy-preview-tags">${result.tags.map((t) => `<span class="vim-fuzzy-tag">${escapeHtml(t)}</span>`).join('')}</div>`
        : ''}
    `;
  } else {
    previewEl.innerHTML = '<div class="vim-fuzzy-preview-placeholder">Select a result to preview</div>';
  }
}

function updateStatus(): void {
  if (!statusEl) return;
  if (results.length === 0) {
    statusEl.textContent = '';
  } else {
    statusEl.textContent = `${results.length} result${results.length === 1 ? '' : 's'}`;
  }
}

function showError(html: string): void {
  if (!resultListEl) return;
  resultListEl.innerHTML = `<div class="vim-fuzzy-error">${html}</div>`;
  if (previewEl) previewEl.innerHTML = '';
  if (statusEl) statusEl.textContent = '';
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
